### ISSUE TITLE
git提问

### ISSUE THREAD

**Issue by mengdodo** [xirong/my-git#40]
Gitflow工作流中的开发是开发新功能再推送到dev,再通过dev推送到master上线，这是一个开发即准备上线的搞法。

我现在遇到一个问题，公司有新功能开发不是按顺序上线的，公司有多个正式环境，内部的功能是交集存在的，例如master_1只有代号1，2的功能，但是master_2上却是1,2,3功能，怎么合理布置开发？

**Comment by xirong** [comment]
一般不会这么玩，master分支就是一个，用来承载最新的验证过的线上代码； 开发时从master拉新分支，feature1，feature2等，多功能可并行开发，单独上线或者合并后上线都可以，这个主要看贵公司的CI流程；

**Comment by mengdodo** [comment]
> @mengdodo 一般不会这么玩，master分支就是一个，用来承载最新的验证过的线上代码； 开发时从master拉新分支，feature1，feature2等，多功能可并行开发，单独上线或者合并后上线都可以，这个主要看贵公司的CI流程；

确实是奇葩搞法，愁死我了
