### ISSUE TITLE
【文档有误】my-git/use-gitlab-github-together.md

### ISSUE THREAD

**Issue by JohnTeslaa** [xirong/my-git#41]
如图：config项应该去掉"git"

![Snipaste_2021-02-28_23-06-08](https://user-images.githubusercontent.com/42859030/109423372-154c6a80-7a1a-11eb-84f9-a997ca125f4b.jpg)

**Comment by JohnTeslaa** [comment]
期待您的回复

**Comment by xirong** [comment]
这个是看自己公司的git仓库地址的域名，这是之前公司的规范； 四级和三级没本质区别，都指的是自己公司git仓库的地址。
