### ISSUE TITLE
如果你的不能这样，至少在功能合并到master分支后能自动关闭Pull Request

### ISSUE THREAD

**Issue by zhubo** [xirong/my-git#6]
如果你的做不到这点，至少要做到在功能合并到master分支后能自动关闭Pull Request

**Comment by xirong** [comment]
Issues are a great way to keep track of tasks, enhancements, and bugs for your projects.  please read for detail [Mastering Issues:](https://guides.github.com/features/issues/) https://guides.github.com/features/issues/  #5 #4 #3 #2 #1

**Comment by zhubo** [comment]
我看了说明，但不明白有什么冲突。我分别报告了一处翻译错误，一处错别字，四处个人觉得可以更顺口的建议。难道要合并到一起吗？这些报告或建议不放这那放哪呢？
