### ISSUE TITLE
如何下载博主的pdf文档呢

### ISSUE THREAD

**Issue by Amandaleae** [xirong/my-git#9]
如何下载博主的pdf文档呢   https://github.com/xirong/my-git/commits/master/ebooks/Git%20Community%20Book.pdf

**Comment by appleboy** [comment]
https://github.com/xirong/my-git/raw/master/ebooks/Git%20Community%20Book.pdf 直接點就可以了吧

**Comment by xirong** [comment]
@Amandaleae  有三种方法，如下：
1.  单纯只要一个文件，就如同 @appleboy  所说，找到文件的url，直接打开就ok。
2.  仓库首页**右上角** `fork` 仓库代码，得到自己的仓库，然后 `git clone git@github.com:yourname/my-git.git` 。
3.  仓库首页 **右下角** `Download ZIP` ，直接下载仓库zip包到你本地。

**Comment by meiqi502** [comment]
https://github.com/meiqi502/book/blob/master/WebKit%E6%8A%80%E6%9C%AF%E5%86%85%E5%B9%95%E6%9C%B1%E6%B0%B8%E7%9B%9B.pdf

**Comment by meiqi502** [comment]
https://github.com/meiqi502/book/raw/master/WebKit%E6%8A%80%E6%9C%AF%E5%86%85%E5%B9%95%E6%9C%B1%E6%B0%B8%E7%9B%9B.pdf

**Comment by Ennis12Noble** [comment]
https://github.com/lfkdsk/PracticeCode/blob/master/Paper/%E9%98%85%E8%AF%BB%E6%96%87%E6%A1%A3/%E8%87%AA%E5%8A%A8%E6%9C%BA%E7%90%86%E8%AE%BA%E3%80%81%E8%AF%AD%E8%A8%80%E5%92%8C%E8%AE%A1%E7%AE%97%E5%AF%BC%E8%AE%BA(%E5%8E%9F%E4%B9%A6%E7%AC%AC3%E7%89%88).pdf

**Comment by ZombieT** [comment]
https://github.com/homerzhou/pdf/blob/master/%E6%B3%9B%E5%9E%8B%E7%BC%96%E7%A8%8B%E4%B8%8ESTL%E4%B8%AD%E6%96%87%E7%89%88.pdf
